### ISSUE TITLE
Error 500: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by cgalant** [catalogueglobal/metadata#2]
I run the shaded jar on my local machine and try to access the following URL : `http://localhost:4400/api/metadata/1.0/secure/license
`
and got a 500 Http error this the following message : 
`java.lang.NoClassDefFoundError: Could not initialize class global.catalogue.metadata.models.License
`
in the logs, I got the following stacktrace : 
```
10:08:01.425 [qtp571621392-21] WARN  org.eclipse.jetty.server.HttpChannel : //local_catalogue-metadata:4400/api/metadata/1.0/secure/license
java.lang.NoClassDefFoundError: Could not initialize class global.catalogue.metadata.models.License
        at global.catalogue.metadata.controllers.api.LicenseController.getAllLicenses(LicenseController.java:38) ~[metadata.jar:na]
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) ~[metadata.jar:na]
        at spark.http.matching.Routes.execute(Routes.java:61) ~[metadata.jar:na]
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126) ~[metadata.jar:na]
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) ~[metadata.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) ~[metadata.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[metadata.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) ~[metadata.jar:na]
        at org.eclipse.jetty.server.Server.handle(Server.java:517) ~[metadata.jar:na]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) ~[metadata.jar:na]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [metadata.jar:na]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [metadata.jar:na]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [metadata.jar:na]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [metadata.jar:na]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [metadata.jar:na]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [metadata.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [metadata.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [metadata.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92-internal]


```

**Comment by zbouziane** [comment]
This is may be due to corrupted MapDB files. We have planned the migration of the persistence layer to a SQL one next week.
